
-- require '野怪.BOSS技能'
-- require '野怪.技能'
-- require '野怪.刷兵规则'
-- require '野怪.掉落'
-- require '野怪.BOSS-AI'
-- require '野怪.BOSS光环'
-- require '野怪.领主'
-- require '野怪.领主-AI'
require '野怪.creep'
require '野怪.刷怪'
require '野怪.掉落'
require '野怪.BOSS-AI'
