require '平台.道具.天使之光'
require '平台.道具.齐天大圣'
require '平台.道具.金币礼包'
require '平台.道具.木材礼包'
require '平台.道具.双倍积分卡'
require '平台.道具.生存会员'
require '平台.道具.小翅膀'
require '平台.道具.杰克'
require '平台.道具.后羿'
require '平台.道具.影歌'
require '平台.道具.王昭君'
require '平台.道具.大天使加百列'

require '平台.道具.寻宝小达人'
require '平台.道具.战斗礼包'
require '平台.道具.资源礼包'
require '平台.道具.穆拉丁'

